[package]
name = "create-multisig-token"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "2.2.6"
solana-sdk = "2.2.2"
dotenvy = "0.15.7"
serde_json = "1.0.140"
spl-token = "8.0.0"
solana-helper = "0.1.0"
spl-associated-token-account = "6.0.0"
